        {
          id: 165,
          title: "Numbers",
          icon: "🧩",
          skillFocus: "Logical Reasoning",
          skillType: "logical",
          color: "from-indigo-500 to-purple-600",
          image: "puzzles/puzzle_165.webp",
          question: "Numbers",
          idealAnswer: "Think step by step and consider all possibilities.",
          keyPrinciples: ["Logical deduction","Pattern recognition"]
        },
        {
          id: 166,
          title: "Divisibility Rules",
          icon: "🧩",
          skillFocus: "Logical Reasoning",
          skillType: "logical",
          color: "from-indigo-500 to-purple-600",
          image: "puzzles/puzzle_166.jpg",
          question: "Divisibility Rules",
          idealAnswer: "Think step by step and consider all possibilities.",
          keyPrinciples: ["Logical deduction","Pattern recognition"]
        },
        {
          id: 167,
          title: "Verbal Ability",
          icon: "🧩",
          skillFocus: "Logical Reasoning",
          skillType: "logical",
          color: "from-indigo-500 to-purple-600",
          image: "puzzles/puzzle_167.png",
          question: "Verbal Ability",
          idealAnswer: "Think step by step and consider all possibilities.",
          keyPrinciples: ["Logical deduction","Pattern recognition"]
        },
        {
          id: 168,
          title: "Logical Reasoning",
          icon: "🧩",
          skillFocus: "Logical Reasoning",
          skillType: "logical",
          color: "from-indigo-500 to-purple-600",
          image: "puzzles/puzzle_168.png",
          question: "Logical Reasoning",
          idealAnswer: "Think step by step and consider all possibilities.",
          keyPrinciples: ["Logical deduction","Pattern recognition"]
        },
        {
          id: 169,
          title: "Coding-Decoding",
          icon: "🧩",
          skillFocus: "Logical Reasoning",
          skillType: "logical",
          color: "from-indigo-500 to-purple-600",
          image: "puzzles/puzzle_169.webp",
          question: "Coding-Decoding",
          idealAnswer: "Think step by step and consider all possibilities.",
          keyPrinciples: ["Logical deduction","Pattern recognition"]
        },
        {
          id: 170,
          title: "Ven Diagrams",
          icon: "🧩",
          skillFocus: "Logical Reasoning",
          skillType: "logical",
          color: "from-indigo-500 to-purple-600",
          image: "puzzles/puzzle_170.webp",
          question: "Ven Diagrams",
          idealAnswer: "Think step by step and consider all possibilities.",
          keyPrinciples: ["Logical deduction","Pattern recognition"]
        },
        {
          id: 171,
          title: "Puzzles",
          icon: "🧩",
          skillFocus: "Logical Reasoning",
          skillType: "logical",
          color: "from-indigo-500 to-purple-600",
          image: "puzzles/puzzle_171.webp",
          question: "Puzzles",
          idealAnswer: "Think step by step and consider all possibilities.",
          keyPrinciples: ["Logical deduction","Pattern recognition"]
        }